#!/bin/bash
# watch/build/restart using watchexec

export DOCKER_API_VERSION=1.38
trap "exit" INT TERM ERR
trap "kill 0" EXIT

watchexec -e .go,.html,.js,.css -s SIGKILL -r  -- go run . &
watchexec -e .ts -- tsc &

wait
